version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - gemini-lb-logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped

volumes:
  gemini-lb-logs:
